exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('vics_japanese_words')
    .del()
    .then(function() {
      // Inserts seed entries
      return knex('vics_japanese_words').insert([
        {
          date: 'Mon, April 1 2019 10:00:00 HST',
          kanji: '爽やか',
          hiragana: 'さわやか',
          romaji: 'sawayaka',
          english: 'refreshing; invigorating',
        },
        {
          date: 'Tue, April 2 2019 10:00:00 HST',
          kanji: '',
          hiragana: 'まめ',
          romaji: 'mame',
          english: 'diligent; hardworking',
        },
        {
          date: 'Wed, April 3 2019 10:00:00 HST',
          kanji: '望ましい',
          hiragana: 'のぞましい',
          romaji: 'nozomashii',
          english: 'desire',
        },
        {
          date: 'Thu, April 4 2019 10:00:00 HST',
          kanji: '物足りない',
          hiragana: 'ものたりない',
          romaji: 'monotari nai',
          english: 'unsatisfied',
        },
        {
          date: 'Fri, April 5 2019 10:00:00 HST',
          kanji: '',
          hiragana: 'まじで',
          romaji: 'maji de',
          english: 'really?',
        },
        {
          date: 'Fri, April 5 2019 10:00:00 HST',
          kanji: '',
          hiragana: 'まじかよ',
          romaji: 'maji ka yo',
          english: "I can't believe it!",
        },
        {
          date: 'Mon, April 8 2019 10:00:00 HST',
          kanji: '',
          hiragana: 'ペイペイ',
          romaji: 'pei pei',
          english: 'inferior; low rank',
        },
        {
          date: 'Tue, April 9 2019 10:00:00 HST',
          kanji: '焦る',
          hiragana: 'あせる',
          romaji: 'aseru',
          english: 'to hurry; panic',
        },
        {
          date: 'Wed, April 10 2019 10:00:00 HST',
          kanji: '四六時中',
          hiragana: 'しろくじちゅう',
          romaji: 'shiroku ji chuu',
          english: 'around the clock; day and night',
        },
        {
          date: 'Thu, April 11 2019 10:00:00 HST',
          kanji: '別腹',
          hiragana: 'べつばら',
          romaji: 'betsubara',
          english: 'dessert stomach; always room for dessert',
        },
        {
          date: 'Fri, April 12 2019 10:00:00 HST',
          kanji: '仲良し',
          hiragana: 'なかよし',
          romaji: 'nakayoshi',
          english: 'good friend; chum; good relations',
        },
        {
          date: 'Mon, April 15 2019 10:00:00 HST',
          kanji: '',
          hiragana: 'ムカつく',
          romaji: 'mukatsuku',
          english: 'to get angry; irritated',
        },
        {
          date: 'Tue, April 16 2019 10:00:00 HST',
          kanji: '',
          hiragana: 'さっぱり わからない',
          romaji: 'sappari wakaranai',
          english: "I don't have a clue",
        },
        {
          date: 'Wed, April 17 2019 10:00:00 HST',
          kanji: '賛成',
          hiragana: 'さんせい',
          romaji: 'sansei',
          english: 'agree; approve; support',
        },
        {
          date: 'Thu, April 18 2019 10:00:00 HST',
          kanji: '',
          hiragana: 'おっす',
          romaji: 'ossu',
          english: "What's up?",
        },
        {
          date: 'Fri, April 19 2019 10:00:00 HST',
          kanji: '渋い',
          hiragana: 'しぶい',
          romaji: 'shibui',
          english: 'very cool; refined; cultured',
        },
        {
          date: 'Mon, April 22 2019 10:00:00 HST',
          kanji: '',
          hiragana: 'くさい',
          romaji: 'kusai',
          english: 'smelly; stinky; bad odor',
        },
        {
          date: 'Tue, April 23 2019 10:00:00 HST',
          kanji: '',
          hiragana: 'おじゃまします',
          romaji: 'ojama shimasu',
          english: 'Sorry for intruding, bothering you',
        },
        {
          date: 'Wed, April 24 2019 10:00:00 HST',
          kanji: '退屈',
          hiragana: 'たいくつ',
          romaji: 'taikutsu',
          english: 'tedious',
        },
        {
          date: 'Thu, April 25 2019 10:00:00 HST',
          kanji: '爆発',
          hiragana: 'ばくはつ',
          romaji: 'bakuhatsu',
          english: 'explosion; detonation; :boom:',
        },
        {
          date: 'Fri, April 26 2019 10:00:00 HST',
          kanji: '一歩先',
          hiragana: 'いっぽさき',
          romaji: 'ippo saki',
          english: 'one step ahead',
        },
        {
          date: 'Mon, April 29 2019 10:00:00 HST',
          kanji: '最高',
          hiragana: 'さいこう',
          romaji: 'saikou',
          english: 'the best, awesome',
        },
        {
          date: 'Tue, April 30 2019 10:00:00 HST',
          kanji: '最低',
          hiragana: 'さいてい',
          romaji: 'saitei',
          english: 'the worst; lowest',
        },
        {
          date: 'Wed, May 1 2019 10:00:00 HST',
          kanji: '応援する',
          hiragana: 'おうえん する',
          romaji: 'ouen suru',
          english: 'to support; to cheer on',
        },
        {
          date: 'Thu, May 2 2019 10:00:00 HST',
          kanji: '自発的',
          hiragana: 'じはつ てき',
          romaji: 'jihatsu teki',
          english: 'spontaneous',
        },
        {
          date: 'Fri, May 3 2019 10:00:00 HST',
          kanji: '',
          hiragana: 'のんびり',
          romaji: 'nonbiri',
          english: 'relax; laid-back; chill',
        },
        {
          date: 'Mon, May 6 2019 10:00:00 HST',
          kanji: '',
          hiragana: 'キモイ',
          romaji: 'kimoi',
          english: 'gross; disgusting',
        },
        {
          date: 'Tue, May 7 2019 10:00:00 HST',
          kanji: '',
          hiragana: 'おわらない',
          romaji: 'owaranai',
          english: 'never-ending',
        },
        {
          date: 'Wed, May 8 2019 10:00:00 HST',
          kanji: '一石二鳥',
          hiragana: 'いっせき にちょう',
          romaji: 'isseki nichou',
          english: 'kill two birds with one stone',
        },
        {
          date: 'Thu, May 9 2019 10:00:00 HST',
          kanji: '',
          hiragana: 'めっちゃ',
          romaji: 'meccha',
          english: 'very; absolutely',
        },
        {
          date: 'Fri, May 10 2019 10:00:00 HST',
          kanji: '我慢',
          hiragana: 'がまん',
          romaji: 'gaman',
          english: 'patience; to endure',
        },
        {
          date: 'Mon, May 13 2019 10:00:00 HST',
          kanji: '',
          hiragana: 'だらだらする',
          romaji: 'dara dara suru',
          english: 'to be lazy; chill; idle',
        },
        {
          date: 'Tue, May 14 2019 10:00:00 HST',
          kanji: '',
          hiragana: 'ばらばら',
          romaji: 'bara bara',
          english: 'scattered; all over the place',
        },
        {
          date: 'Wed, May 15 2019 10:00:00 HST',
          kanji: '',
          hiragana: 'バタバタ',
          romaji: 'bata bata',
          english: 'busy; busyness',
        },
        {
          date: 'Thu, May 16 2019 10:00:00 HST',
          kanji: '行方不明',
          hiragana: 'ゆくえ　ふめい',
          romaji: 'yukue fumei',
          english: 'missing',
        },
        {
          date: 'Fri, May 17 2019 10:00:00 HST',
          kanji: '最後尾',
          hiragana: 'さいこうび',
          romaji: 'saikoubi',
          english: 'end of the line; last',
        },
        {
          date: 'Mon, May 20 2019 10:00:00 HST',
          kanji: '五分五分',
          hiragana: 'ごぶ ごぶ',
          romaji: 'gobu gobu',
          english: '50/50; even; tie',
        },
        {
          date: 'Tue, May 21 2019 10:00:00 HST',
          kanji: '探す',
          hiragana: 'さがす',
          romaji: 'sagasu',
          english: 'to search; to look for',
        },
        {
          date: 'Wed, May 22 2019 10:00:00 HST',
          kanji: '',
          hiragana: 'ぼろぼろ',
          romaji: 'boro boro',
          english: 'worn-out; shabby',
        },
        {
          date: 'Thu, May 23 2019 10:00:00 HST',
          kanji: '',
          hiragana: 'さっぱり',
          romaji: 'sappari',
          english: 'fresh; clean; neat',
        },
        {
          date: 'Fri, May 24 2019 10:00:00 HST',
          kanji: '',
          hiragana: 'ぱりぱり',
          romaji: 'pari pari',
          english: 'crispy',
        },
        {
          date: 'Sat, May 25 2019 10:00:00 HST',
          kanji: '暗い',
          hiragana: 'くらい',
          romaji: 'kurai',
          english: 'dark',
        },
        {
          date: 'Mon, May 27 2019 10:00:00 HST',
          kanji: '諦める',
          hiragana: 'あきらめる',
          romaji: 'akirameru',
          english: 'give up; resign',
        },
        {
          date: 'Tue, May 28 2019 10:00:00 HST',
          kanji: '信じられない',
          hiragana: 'しんじられない',
          romaji: 'shinjirarenai',
          english: 'unbelievable',
        },
        {
          date: 'Wed, May 29 2019 10:00:00 HST',
          kanji: '守る',
          hiragana: 'まもる',
          romaji: 'mamoru',
          english: 'to protect',
        },
        {
          date: 'Thu, May 30 2019 10:00:00 HST',
          kanji: 'さまざまな方向に引っ張られている',
          hiragana: 'さまざま な ほうこう に ひっぱられて いる',
          romaji: 'samazama na houkou ni hippararete iru',
          english: 'being pulled in many directions',
        },
        {
          date: 'Fri, May 31 2019 10:00:00 HST',
          kanji: '奇跡',
          hiragana: 'きせき',
          romaji: 'kiseki',
          english: 'miracle; wonder; marvel',
        },
        {
          date: 'Mon, June 3 2019 10:00:00 HST',
          kanji: '',
          hiragana: 'やっと',
          romaji: 'yatto',
          english: 'finally; at last',
        },
        {
          date: 'Tue, June 4 2019 10:00:00 HST',
          kanji: '',
          hiragana: 'いまさら',
          romaji: 'ima sara',
          english: 'last minute; at this late hour',
        },
        {
          date: 'Wed, June 5 2019 10:00:00 HST',
          kanji: '',
          hiragana: 'いきなり',
          romaji: 'ikinari',
          english: 'abruptly; all of a sudden; spur of the moment',
        },
        {
          date: 'Thu, June 6 2019 10:00:00 HST',
          kanji: '',
          hiragana: 'ばっちり',
          romaji: 'bacchiri',
          english: 'perfect; complete; right on the mark',
        },
        {
          date: 'Fri, June 7 2019 10:00:00 HST',
          kanji: '文句する',
          hiragana: 'もんくする',
          romaji: 'monku suru',
          english: 'to complain',
        },
        {
          date: 'Mon, June 10 2019 10:00:00 HST',
          kanji: '偉い',
          hiragana: 'えらい',
          romaji: 'erai',
          english: 'great; admirable; authoritative',
        },
        {
          date: 'Tue, June 11 2019 10:00:00 HST',
          kanji: '大爆笑',
          hiragana: 'だいばくしょう',
          romaji: 'daibakushou',
          english: 'erupt in laughter; LOL',
        },
        {
          date: 'Wed, June 12 2019 10:00:00 HST',
          kanji: '眩しい',
          hiragana: 'まぶしい',
          romaji: 'mabushii',
          english: 'bright; blinding; dazzling',
        },
        {
          date: 'Thu, June 13 2019 10:00:00 HST',
          kanji: '',
          hiragana: 'そろそろ',
          romaji: 'soro soro',
          english: 'it’s about time; pretty soon',
        },
        {
          date: 'Fri, June 14 2019 10:00:00 HST',
          kanji: '朝飯前',
          hiragana: 'あさめしまえ',
          romaji: 'asa meshi mae',
          english: "piece of cake; child's play",
        },
        {
          date: 'Mon, June 17 2019 10:00:00 HST',
          kanji: '優秀',
          hiragana: 'ゆうしゅう',
          romaji: 'yuushuu',
          english: 'excellent; superior',
        },
      ]);
    });
};
